### Infrastructure services ###

version: '3.1'
services:

  ### FRONTEND ###
  weather-forecast-frontend-container:
    image: weatherforecast/weather-forecast-frontend:latest
    container_name: weather-forecast-frontend
    ports:
      - "80:80"
    tty: true
    expose:
      - "80"
    depends_on:
      - weather-forecast-backend-container
    stdin_open: true
    environment:
      - MODE=dev
    networks:
      - local

  ### BACKEND ###
  weather-forecast-backend-container:
    image: weatherforecast/weather-forecast-backend-webapplication:1.0-SNAPSHOT
    container_name: weather-forecast-backend
    volumes:
      - /data/weather-forecast-backend
    ports:
      - "8080:8080"
    depends_on:
      - weatherforecast-configserver-container
    restart: always
    networks:
      - local

  ### CONFIG SERVERS ###
  weatherforecast-configserver-container:
    image: weatherforecast/weather-forecast-config-server:1.0-SNAPSHOT
    container_name: weatherforecast-configserver
    volumes:
      - /data/weatherforecast-configserver
    networks:
      - local
    ports:
      - "8888:8888"
      - "8889:8889"

networks:
  local:
    driver: bridge